### 1. Conv1D

In [10]:
import torch
import torch.nn as nn

# 输入序列：batch_size=1, sequence_length=10, input_channels=2
input_data = torch.randn(1, 10, 2)
print(input_data)

# 定义 Conv1D 层：input_channels=2, output_channels=4, kernel_size=3
conv1d_layer = nn.Conv1d(in_channels=2, out_channels=4, kernel_size=3)

# 转置输入数据的形状以匹配 Conv1D 的输入要求
input_data = input_data.permute(0, 2, 1)  # [batch_size, input_channels, sequence_length]
print(input_data)

# 应用 Conv1D
output_data = conv1d_layer(input_data)
print(output_data)

print("Conv1D 输出形状:", output_data.shape)  # 输出形状: [1, 4, 8]

print(output_data.transpose(1, 2))

tensor([[[ 0.1527,  0.3765],
         [-1.7406,  1.2127],
         [ 1.0000,  0.2734],
         [ 0.5057, -0.5801],
         [-1.6769, -0.1542],
         [-0.5450, -0.2491],
         [ 0.7273,  0.9571],
         [-0.2029,  0.8794],
         [ 0.7846,  1.6587],
         [ 0.6736, -0.4857]]])
tensor([[[ 0.1527, -1.7406,  1.0000,  0.5057, -1.6769, -0.5450,  0.7273,
          -0.2029,  0.7846,  0.6736],
         [ 0.3765,  1.2127,  0.2734, -0.5801, -0.1542, -0.2491,  0.9571,
           0.8794,  1.6587, -0.4857]]])
tensor([[[-1.0694, -0.4982,  0.5013, -0.3891, -0.7848, -0.4428, -0.4555,
          -0.5499],
         [ 1.0165, -1.4814,  0.0024,  0.9811,  0.0135,  0.0031,  0.9104,
          -0.5174],
         [-1.0576,  0.5480,  0.6876, -0.5180, -0.6212, -0.5454, -0.6343,
          -0.1134],
         [-0.4210, -0.2407,  0.9431, -0.0988, -0.6405,  0.4580,  0.3693,
           0.3150]]], grad_fn=<ConvolutionBackward0>)
Conv1D 输出形状: torch.Size([1, 4, 8])
tensor([[[-1.0694,  1.0165, -1.0576, -0.421

### 2. Linear

In [6]:
import torch
import torch.nn as nn

# 输入数据：batch_size=1, input_features=10
input_data = torch.randn(1, 10)
print(input_data)

# 定义 Linear 层：input_features=10, output_features=5
linear_layer = nn.Linear(in_features=10, out_features=5)

# 应用 Linear 层
output_data = linear_layer(input_data)
print(output_data)

print("Linear 输出形状:", output_data.shape)  # 输出形状: [1, 5]

print(output_data.transpose(0, 1))

tensor([[ 0.2343,  1.0328,  0.3631,  0.3492, -1.0601, -0.0025,  0.1716, -1.3771,
          0.0853, -1.5605]])
tensor([[ 0.5578, -0.1334, -0.3939,  0.4101,  0.2022]],
       grad_fn=<AddmmBackward0>)
Linear 输出形状: torch.Size([1, 5])
